version: 2
updates:

# raygun4node-aws-lambda
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

# example
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Package in example is accessed by path, 
      # do not update in package.json.
      - dependency-name: "@raygun.io/aws-lambda"

# Github Actions dependencies updates config
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
